version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - backend

  django:
    image: python:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/code
    command: bash -c "pip install -r /code/requirements.txt && python /code/SistemaIntegradoColegio/manage.py migrate && python /code/SistemaIntegradoColegio/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  postgres_data: