# Generated by Django 4.2.13 on 2024-06-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ie', models.CharField(max_length=20, unique=True)),
                ('vision', models.TextField()),
                ('mision', models.TextField()),
                ('direccion', models.TextField()),
                ('nombre', models.TextField()),
                ('programa_educativo', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='instituciones_educativas')),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red_social', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo_redes_sociales')),
                ('url', models.URLField()),
                ('institucion_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.institucioneducativa')),
            ],
        ),
    ]
