# Generated by Django 4.2.13 on 2024-06-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitucionEducativa',
            new_name='Institucion',
        ),
    ]
