# Generated by Django 4.2.13 on 2024-06-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0002_rename_institucioneducativa_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('imagen_sede', models.ImageField(upload_to='sedes')),
                ('horario_atencion', models.TextField()),
                ('publicado', models.BooleanField(default=False)),
                ('institucion_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.institucion')),
            ],
        ),
    ]
